// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9VHIH7r8ZxcAZPu06s9vK3uvcm_YsrTQ',
    appId: '1:487505250025:web:32ed0337de370ada375278',
    messagingSenderId: '487505250025',
    projectId: 'bookfinal',
    authDomain: 'bookfinal.firebaseapp.com',
    storageBucket: 'bookfinal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFcrAqjPwBFuUr1s2N2bCYQpP8v5JzrEM',
    appId: '1:487505250025:android:26de2b2365b197e8375278',
    messagingSenderId: '487505250025',
    projectId: 'bookfinal',
    storageBucket: 'bookfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GWvh2CUsNhT6k_0mO9tq2rb9-wvyzP8',
    appId: '1:487505250025:ios:c4cd283aabbd2140375278',
    messagingSenderId: '487505250025',
    projectId: 'bookfinal',
    storageBucket: 'bookfinal.appspot.com',
    iosClientId: '487505250025-0lu6mslus1mpgk0srbuhp7j6dp4hhn57.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-GWvh2CUsNhT6k_0mO9tq2rb9-wvyzP8',
    appId: '1:487505250025:ios:c4cd283aabbd2140375278',
    messagingSenderId: '487505250025',
    projectId: 'bookfinal',
    storageBucket: 'bookfinal.appspot.com',
    iosClientId: '487505250025-0lu6mslus1mpgk0srbuhp7j6dp4hhn57.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksApp',
  );
}
